<?php

namespace Pax\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ContasReceberRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContasReceberRepository extends EntityRepository
{
}
