<?php

namespace Pax\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * FuncionariosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FuncionariosRepository extends EntityRepository
{
}
