<?php

namespace Pax\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MoedasRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MoedasRepository extends EntityRepository
{
}
