<?php

namespace Admin\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ArquivosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArquivosRepository extends EntityRepository
{
}
