<?php

namespace Admin\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ClientesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClientesRepository extends EntityRepository
{
}
