<?php

namespace Admin\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ServicosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ServicosRepository extends EntityRepository
{
}
