<?php

namespace Admin\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ConteudosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConteudosRepository extends EntityRepository
{
}
